server:
    port: 8888

spring:
  cloud:
    config:
        server:
          git:
            uri: https://github.com/dabai-cai/yohjr/
            searchPaths: /server/src/main/resources/
            username: dabai-cai
            password: asd456++
  application:
    name: config-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
